version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: $(npm bin)/ts-node -vv
      - run: npm ls --depth 0
      - run: npm run bootstrap:ci
      - run: npm run ci
      - run: bash <(curl -s https://codecov.io/bash)
